-- DROP TABLE IF EXISTS TIPOCOLUNA CASCADE;
-- CREATE TABLE IF NOT EXISTS TIPOCOLUNA(
-- 	ID SERIAL primary KEY,
-- 	DESCRICAO VARCHAR(50) NOT NULL,
-- 	EXCLUIDO BIT NOT NULL DEFAULT '0'
-- );

DROP TABLE IF exists CATEGORIA CASCADE;
create table if not exists CATEGORIA (
	ID SERIAL primary key,
	DESCRICAO VARCHAR (70) not NULL,
	ATIVA BIT NOT NULL,
	EXCLUIDO BIT NOT NULL DEFAULT '0'
);

drop table if exists tabela CASCADE;
create table if not exists tabela(
	ID SERIAL primary key,
	NOME VARCHAR (70) not NULL,
	ATIVA BIT NOT NULL DEFAULT '1',
	CATEGORIA_ID INT DEFAULT NULL,
	FOREIGN KEY (CATEGORIA_ID) references CATEGORIA(ID),
	EXCLUIDO BIT NOT NULL DEFAULT '0'
);

DROP TABLE IF EXISTS COLUNA CASCADE;
CREATE TABLE COLUNA(
	ID SERIAL primary KEY,
	NOME VARCHAR(255),
	VAZIO BIT NOT NULL,
	TIPO_COLUNA VARCHAR(30),
	-- ID_TIPOCOLUNA INT NOT NULL,
	-- FOREIGN KEY (ID_TIPOCOLUNA) references TIPOCOLUNA(ID),
	ID_TABELA INT NOT NULL,
	FOREIGN KEY (ID_TABELA) REFERENCES TABELA(ID),
	EXCLUIDO BIT NOT NULL DEFAULT '0'
);

-- DROP TABLE IF EXISTS COLUNA CASCADE;
-- CREATE TABLE COLUNA(
-- 	ID SERIAL primary KEY,
-- 	NOME VARCHAR(255),
-- 	VAZIO BIT NOT NULL,
-- 	TIPO VARCHAR(50),
-- 	ID_TABELA INT NOT NULL,
-- 	FOREIGN KEY (ID_TABELA) REFERENCES TABELA(ID),
-- 	EXCLUIDO BIT NOT NULL DEFAULT '0'
-- );

DROP TABLE IF EXISTS PLANILHA_EXCEL CASCADE;
CREATE TABLE IF NOT EXISTS PLANILHA_EXCEL(
	ID SERIAL PRIMARY KEY,
	DESCRICAO VARCHAR(150) NOT NULL,
	QTD_REGISTROS INT NOT NULL,
	TABELA_ID INT NOT NULL,
	FOREIGN KEY(TABELA_ID) REFERENCES TABELA(ID),
	EXCLUIDO BIT NOT NULL DEFAULT '0'
);

DROP TABLE IF EXISTS MENSAGEM_IMPORTACAO CASCADE;
CREATE TABLE IF NOT EXISTS MENSAGEM_IMPORTACAO(
	ID SERIAL PRIMARY KEY,
	DESCRICAO VARCHAR(255),
	EXCLUIDO BIT NOT NULL DEFAULT '0'
);

DROP TABLE IF EXISTS LOGIMPORTACAO;
CREATE TABLE IF NOT EXISTS LOGIMPORTACAO(
	ID SERIAL PRIMARY KEY,
	NOME_TABELA VARCHAR(70) NOT NULL,
	NOME_USUARIO VARCHAR(100) NOT NULL,
	DATA_HORA TIMESTAMP NOT NULL,
	MENSAGEM_IMPORTACAO_ID INT NOT NULL,
	FOREIGN KEY (MENSAGEM_IMPORTACAO_ID) REFERENCES MENSAGEM_IMPORTACAO(ID),
	PLANILHA_EXCEL_ID INT NOT NULL,
	FOREIGN KEY (PLANILHA_EXCEL_ID) REFERENCES PLANILHA_EXCEL(ID),
	EXCLUIDO BIT NOT NULL DEFAULT '0'
);

DROP TABLE IF EXISTS TAG CASCADE;
CREATE TABLE IF NOT EXISTS TAG(
	ID SERIAL PRIMARY KEY,
	DESCRICAO VARCHAR(70) NOT NULL,
	EXCLUIDO BIT NOT NULL DEFAULT '0'
);

DROP TABLE IF EXISTS CATEGORIA_TAG;
CREATE TABLE IF NOT EXISTS CATEGORIA_TAG(
	ID SERIAL PRIMARY KEY,
	CATEGORIA_ID INT NOT NULL,
	FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA(ID),
	TAG_ID INT NOT NULL,
	FOREIGN KEY (TAG_ID) REFERENCES TAG(ID),
	EXCLUIDO BIT NOT NULL DEFAULT '0'
);

DROP TABLE IF EXISTS TABELA_TAG;
CREATE TABLE IF NOT EXISTS TABELA_TAG(
	ID SERIAL PRIMARY KEY,
	TABELA_ID INT NOT NULL,
	FOREIGN KEY (TABELA_ID) REFERENCES TABELA(ID),
	TAG_ID INT NOT NULL,
	FOREIGN KEY (TAG_ID) REFERENCES TAG(ID),
	EXCLUIDO BIT NOT NULL DEFAULT '0'
);

DROP TABLE IF EXISTS OPERACAO CASCADE;
CREATE TABLE IF NOT EXISTS OPERACAO(
	ID SERIAL PRIMARY KEY,
	-- AQUI PROVAVELMENTE VAI TER QUE SER UM TEXT
	OPERACAO TEXT NOT NULL,
	DATA_HORA TIMESTAMP NOT NULL,
	EXCLUIDO BIT NOT NULL DEFAULT '0'
);

DROP TABLE IF EXISTS DEPARTAMENTO CASCADE;
CREATE TABLE IF NOT EXISTS DEPARTAMENTO(
	ID SERIAL PRIMARY KEY,
	DESCRICAO VARCHAR(100) NOT NULL,
	ATIVO BIT NOT NULL,
	EXCLUIDO BIT NOT NULL DEFAULT '0'
);

DROP TABLE IF EXISTS USUARIO CASCADE;
CREATE TABLE IF NOT EXISTS USUARIO(
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(80) NOT NULL,
	ATIVO BIT NOT NULL DEFAULT '1',
	SENHA VARCHAR NOT NULL,
	DEPARTAMENTO_ID INT DEFAULT NULL,
	FOREIGN KEY (DEPARTAMENTO_ID) REFERENCES DEPARTAMENTO(ID),
	EXCLUIDO BIT NOT NULL DEFAULT '0'
);

DROP TABLE IF EXISTS TABELA_OPERACAO_USUARIO;
CREATE TABLE IF NOT EXISTS TABELA_OPERACAO_USUARIO(
	ID SERIAL PRIMARY KEY,
	OPERACAO_ID INT NOT NULL,
	FOREIGN KEY (OPERACAO_ID) REFERENCES OPERACAO(ID),
	TABELA_ID INT NOT NULL,
	FOREIGN KEY (TABELA_ID) REFERENCES TABELA(ID),
	USUARIO_ID INT NOT NULL,
	FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID),
	EXCLUIDO BIT NOT NULL DEFAULT '0'
);

DROP TABLE IF EXISTS DIREITO_LEITURA_ESCRITA CASCADE;
CREATE TABLE IF NOT EXISTS DIREITO_LEITURA_ESCRITA(
	ID SERIAL PRIMARY KEY,
	DESCRICAO VARCHAR(50),
	EXCLUIDO BIT NOT NULL DEFAULT '0'
);

DROP TABLE IF EXISTS LIBERA_DIREITO_LEITURA_ESCRITA_TABELA_USUARIO;
CREATE TABLE IF NOT EXISTS LIBERA_DIREITO_LEITURA_ESCRITA_TABELA_USUARIO(
	ID SERIAL PRIMARY KEY,
	DIREITO_LEITURA_ESCRITA_ID INT NOT NULL,
	FOREIGN KEY (DIREITO_LEITURA_ESCRITA_ID) REFERENCES DIREITO_LEITURA_ESCRITA(ID),
	TABELA_ID INT NOT NULL,
	FOREIGN KEY (TABELA_ID) REFERENCES TABELA(ID),
	USUARIO_ID INT NOT NULL,
	FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID),
	EXCLUIDO BIT NOT NULL DEFAULT '0'
);

DROP TABLE IF EXISTS TIPO_ACESSO CASCADE;
CREATE TABLE IF NOT EXISTS TIPO_ACESSO (
	ID SERIAL PRIMARY KEY,
	DESCRICAO VARCHAR(50),
	EXCLUIDO BIT NOT NULL DEFAULT '0'
);

DROP TABLE IF EXISTS USUARIO_TIPO_ACESSO;
CREATE TABLE IF NOT EXISTS USUARIO_TIPO_ACESSO(
	ID SERIAL PRIMARY KEY,
	USUARIO_ID INT NOT NULL,
	FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID),
	TIPO_ACESSO_ID INT NOT NULL,
	FOREIGN KEY (TIPO_ACESSO_ID) REFERENCES TIPO_ACESSO(ID),
	EXCLUIDO BIT NOT NULL DEFAULT '0'
);

DROP TABLE IF EXISTS LOG_SISTEMA;
CREATE TABLE IF NOT EXISTS LOG_SISTEMA(
	ID SERIAL PRIMARY KEY,
	CAMPO VARCHAR(255) NOT NULL,
	USUARIO VARCHAR(100) NOT NULL,
	VALOR_ANTIGO VARCHAR NOT NULL,
	VALOR_NOVO VARCHAR NOT NULL,
	DATA_HORA TIMESTAMP NOT NULL,
	TABELA VARCHAR(100),
	EXCLUIDO BIT NOT NULL DEFAULT '0'
);
